version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - contextcheck
    - copyloopvar
    - errcheck
    - errchkjson
    - ginkgolinter
    - govet
    - ineffassign
    - loggercheck
    - misspell
    - prealloc
    - perfsprint
    - sloglint
    - staticcheck
    - unused
    - whitespace
    - gosec
formatters:
  enable:
    - gofmt
    - goimports
