version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - errcheck
    - errchkjson
    - govet
    - ineffassign
    - misspell
    - prealloc
    - sloglint
    - staticcheck
    - unused
formatters:
  enable:
    - gofmt
    - goimports
