== RHTAP Multi Arch Controller

This controller orchestrates remote agents for RTHAP. It watches for `TaskRun` instances with the `build.appstudio.redhat.com/multi-arch-required` label, and will then supply SSH credentials for a node of the requested architecture. The `TaskRun` can then use this node to build using a different architecture. When the `TaskRun` is done the controller deals with cleanup up the remote node.

== Try It Out

At present this is deployed on RHTAP Staging. An example of a Multi Arch Pull Request is located at: https://github.com/stuartwdouglas/devfile-sample-go-basic/pull/3

To try this out you need to make similar modifications to your pipeline. The key changes are:

- Add the `-amd64` suffix to the end of all existing references to `$(tasks.build-container.results.IMAGE_URL)`. As there are now multiple images being produces we need a way to distinguish them.
- Rename the `build-container` task to `build-container-amd64`, and change the `runAfter` for all existing checks (clair, snyk etc) to reference this new name.
- Add a `build-container-arm64` task that references the `buildah-remote` task to build the arm image. The details can be seen in the linked pr.
- Add a new `build-container` step that will merge the two images into a multi arch image.

All of this is subject to change.

== How it works

=== The Buildah Remote Task

The `buildah-remote` task runs the container build step of the existing buildah task via ssh on a remote host. This task is currently created programatically by `cmd/taskgen/main.go`. The task has the following differences from the standard buildah task:

- It has an `ARCH` parameter that is used by the controller to decide which host to provision for the build.
- The `build-container` task has been modified to be run remotely over SSH. The workspace is copied to the remote host, the build is done via podman, and then the image copied back. The commands run on the remote host are largely the same as the existing buildah task, just executed via podman.
- It expects the creation of a secret with the name `multi-arch-ssh-$(context.taskRun.name)` to be created by the controller. This secret will have an `id_rsa` private key, and the name of the host to connect to. If no host is available it contains an error message so the task does not wait forever.






