apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - "../../operator"
 - "../../otp"
 - host-config.yaml
 - servicemonitor.yaml
 - servicemonitor_rbac.yaml

images:
  - name: multi-platform-controller
    newName: quay.io/QUAY_USERNAME/multi-platform-controller
    newTag: dev
  - name: multi-platform-otp-server
    newName: quay.io/QUAY_USERNAME/multi-platform-otp
    newTag: dev

