#Task that is used to deploy artifacts by the controller
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: apheleia-deploy
spec:
  description: >-
    This Task can be used to deploy rebuilt artifacts to a maven repository.
  params:
    - name: DOMAIN
      type: string
    - name: OWNER
      type: string
    - name: REPO
      type: string
    - name: ARTIFACT
      type: string
      default: "all"
    - name: FORCE
      type: string
      default: false
  steps:
    - name: deploy
      image: apheleia-processor
      imagePullPolicy: Always
      args:
        - "deploy"
        - "--domain"
        - $(params.DOMAIN)
        - "--owner"
        - $(params.OWNER)
        - "--repo"
        - $(params.REPO)
        - "--force"
        - $(params.FORCE)
        - "--artifact"
        - $(params.ARTIFACT)
      env:
        - name: QUAY_TOKEN
          valueFrom:
            secretKeyRef:
              name: jvm-build-image-secrets
              key: .dockerconfigjson
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: access-key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: secret-key
