apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: multi-platform-controller
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-service
  namespace: multi-platform-controller
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
      app: multi-platform-controller
