apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  annotations:
    appstudio.openshift.io/snapshot: my-app-w92sw
    build.appstudio.openshift.io/repo: https://github.com/nodeshift-starters/devfile-sample?rev=1879fa9159b28f63265dad2cd618c3d0ffd03e79
    build.appstudio.redhat.com/bundle: quay.io/redhat-appstudio-tekton-catalog/pipeline-docker-build:35642514a64075bbfed77db63d5bcdf81fab1da0
    build.appstudio.redhat.com/cloud-address: 169.63.178.13
    build.appstudio.redhat.com/commit_sha: 1879fa9159b28f63265dad2cd618c3d0ffd03e79
    build.appstudio.redhat.com/pipeline_name: docker-build
    build.appstudio.redhat.com/target_branch: main
    chains.tekton.dev/signed: "true"
    pipeline.tekton.dev/release: 876b81e
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: image-build, appstudio, hacbs
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    app.kubernetes.io/version: "0.1"
    appstudio.openshift.io/application: my-app
    appstudio.openshift.io/component: devfile-sample
    build.appstudio.redhat.com/build_type: docker
    pipelines.appstudio.openshift.io/type: build
    pipelines.openshift.io/runtime: generic
    pipelines.openshift.io/strategy: docker
    pipelines.openshift.io/used-by: build-cloud
    tekton.dev/memberOf: tasks
    tekton.dev/pipeline: pipeline-bv572
    tekton.dev/pipelineRun: pipeline-bv572
    tekton.dev/pipelineTask: build-container
    tekton.dev/task: buildah-remote-oci-ta
  generateName: build-remote-container-
  namespace: test-jvm-namespace
spec:
  params:
  - name: IMAGE
    value: quay.io/sdouglas/artifact-deployments:arm64-build
  - name: DOCKERFILE
    value: Dockerfile
  - name: CONTEXT
    value: .
  - name: HERMETIC
    value: "false"
  - name: PREFETCH_INPUT
    value: ""
  - name: IMAGE_EXPIRES_AFTER
    value: ""
  - name: COMMIT_SHA
    value: df0d9e673c67ee0b251fdd349e6c4b4871a1a195
  - name: PLATFORM
    value: linux/s390x
  - name: SOURCE_ARTIFACT
    value: oci:quay.io/sdouglas/artifact-deployments@sha256:b0b4ac91652ccf516af6bf377f55ff999d28b648bfc92ea1082bbd2daf3c968a
  - name: CACHI2_ARTIFACT
    value: oci:quay.io/sdouglas/artifact-deployments@sha256:85cea451eec057fa7e734548ca3ba6d779ed5836a3f9de14b8394575ef0d7d8e
  - name: OCI_STORAGE
    value: quay.io/sdouglas/artifact-deployments:ppc64le-build-prefetch
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: buildah-remote-oci-ta
  timeout: 1h0m0s
