apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    appstudio.openshift.io/snapshot: my-app-w92sw
    build.appstudio.openshift.io/repo: https://github.com/nodeshift-starters/devfile-sample?rev=1879fa9159b28f63265dad2cd618c3d0ffd03e79
    build.appstudio.redhat.com/bundle: quay.io/redhat-appstudio-tekton-catalog/pipeline-docker-build:35642514a64075bbfed77db63d5bcdf81fab1da0
    build.appstudio.redhat.com/commit_sha: 1879fa9159b28f63265dad2cd618c3d0ffd03e79
    build.appstudio.redhat.com/pipeline_name: docker-build
    build.appstudio.redhat.com/target_branch: main
  generateName: devfile-sample-
  labels:
    appstudio.openshift.io/application: my-app
    appstudio.openshift.io/component: devfile-sample
    pipelines.appstudio.openshift.io/type: build
    pipelines.openshift.io/runtime: generic
    pipelines.openshift.io/strategy: docker
    pipelines.openshift.io/used-by: build-cloud
    tekton.dev/pipeline: docker-build
    build.appstudio.redhat.com/target-architecture: arm64
spec:
  params:
  - name: dockerfile
    value: Dockerfile
  - name: git-url
    value: https://github.com/nodeshift-starters/devfile-sample.git
  - name: output-image
    value: quay.io/sdouglas/multi-arch-resolver:arm-build
  - name: path-context
    value: .
  - name: revision
    value: main
  - name: skip-checks
    value: "true"
  - name: rebuild
    value: "true"
  pipelineSpec:
      finally:
        - name: show-sbom
          params:
            - name: IMAGE_URL
              value: $(tasks.build-container.results.IMAGE_URL)
          taskRef:
            kind: Task
            params:
              - name: name
                value: show-sbom
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-show-sbom:0.1@sha256:7db0af43dcebaeb33e34413148370e17078c30fd2fc78fb84c8941b444199f36
              - name: kind
                value: task
            resolver: bundles
        - name: show-summary
          params:
            - name: pipelinerun-name
              value: devfile-sample-h4lt5
            - name: git-url
              value: $(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)
            - name: image-url
              value: quay.io/sdouglas/multi-arch-resolver:arm-build
            - name: build-task-status
              value: $(tasks.build-container.status)
          taskRef:
            kind: Task
            params:
              - name: name
                value: summary
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-summary:0.1@sha256:bd6a2285974541df01260deca99a84b3b48a6b40759049e7e41e96b4942d83d3
              - name: kind
                value: task
            resolver: bundles
      params:
        - description: Source Repository URL
          name: git-url
          type: string
        - default: ""
          description: Revision of the Source Repository
          name: revision
          type: string
        - description: Fully Qualified Output Image
          name: output-image
          type: string
        - default: .
          description: The path to your source code
          name: path-context
          type: string
        - default: Dockerfile
          description: Path to the Dockerfile
          name: dockerfile
          type: string
        - default: "true"
          description: Force rebuild image
          name: rebuild
          type: string
        - default: "false"
          description: Skip checks against built image
          name: skip-checks
          type: string
        - default: "true"
          description: Skip optional checks, set false if you want to run optional checks
          name: skip-optional
          type: string
        - default: "false"
          description: Execute the build with network isolation
          name: hermetic
          type: string
        - default: ""
          description: Build dependencies to be prefetched by Cachi2
          name: prefetch-input
          type: string
        - default: "false"
          description: Java build
          name: java
          type: string
        - default: ""
          description: Image tag expiration time, time values could be something like
            1h, 2d, 3w for hours, days, and weeks, respectively.
          name: image-expires-after
          type: string
      results:
        - description: ""
          name: IMAGE_URL
          value: $(tasks.build-container.results.IMAGE_URL)
        - description: ""
          name: IMAGE_DIGEST
          value: $(tasks.build-container.results.IMAGE_DIGEST)
        - description: ""
          name: CHAINS-GIT_URL
          value: $(tasks.clone-repository.results.url)
        - description: ""
          name: CHAINS-GIT_COMMIT
          value: $(tasks.clone-repository.results.commit)
        - description: ""
          name: JAVA_COMMUNITY_DEPENDENCIES
          value: $(tasks.build-container.results.JAVA_COMMUNITY_DEPENDENCIES)
      tasks:
        - name: init
          params:
            - name: image-url
              value: quay.io/sdouglas/multi-arch-resolver:arm-build
            - name: rebuild
              value: "true"
            - name: skip-checks
              value: "true"
            - name: skip-optional
              value: "true"
            - name: pipelinerun-name
              value: devfile-sample-h4lt5
            - name: pipelinerun-uid
              value: 8cab504d-4fb0-4b4e-9571-681481ba9003
          taskRef:
            kind: Task
            params:
              - name: name
                value: init
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-init:0.1@sha256:26586a7ef08c3e86dfdaf0a5cc38dd3d70c4c02db1331b469caaed0a0f5b3d86
              - name: kind
                value: task
            resolver: bundles
        - name: clone-repository
          params:
            - name: url
              value: https://github.com/nodeshift-starters/devfile-sample.git
            - name: revision
              value: main
          runAfter:
            - init
          taskRef:
            kind: Task
            params:
              - name: name
                value: git-clone
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-git-clone:0.1@sha256:44260edd7da429a3bca3843be5049a15f05f658d1e9766521379e067e972c1e0
              - name: kind
                value: task
            resolver: bundles
          when:
            - input: $(tasks.init.results.build)
              operator: in
              values:
                - "true"
          workspaces:
            - name: output
              workspace: workspace
            - name: basic-auth
              workspace: git-auth
        - name: prefetch-dependencies
          params:
            - name: input
              value: ""
          runAfter:
            - clone-repository
          taskRef:
            kind: Task
            params:
              - name: name
                value: prefetch-dependencies
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-prefetch-dependencies:0.1@sha256:7851457b29fc187c8027fd53ed4f54c6e3a2e9fb0fd85da058022c6fd4dce1b1
              - name: kind
                value: task
            resolver: bundles
          when:
            - input: "false"
              operator: in
              values:
                - "true"
          workspaces:
            - name: source
              workspace: workspace
        - name: build-container
          params:
            - name: IMAGE
              value: quay.io/sdouglas/multi-arch-resolver:arm-build
            - name: DOCKERFILE
              value: Dockerfile
            - name: CONTEXT
              value: .
            - name: HERMETIC
              value: "false"
            - name: PREFETCH_INPUT
              value: ""
            - name: IMAGE_EXPIRES_AFTER
              value: ""
            - name: COMMIT_SHA
              value: $(tasks.clone-repository.results.commit)
          runAfter:
            - prefetch-dependencies
          taskRef:
            kind: Task
            name: buildah-remote
          when:
            - input: $(tasks.init.results.build)
              operator: in
              values:
                - "true"
          workspaces:
            - name: source
              workspace: workspace
        - name: inspect-image
          params:
            - name: IMAGE_URL
              value: $(tasks.build-container.results.IMAGE_URL)
            - name: IMAGE_DIGEST
              value: $(tasks.build-container.results.IMAGE_DIGEST)
          runAfter:
            - build-container
          taskRef:
            kind: Task
            params:
              - name: name
                value: inspect-image
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-inspect-image:0.1@sha256:8b0b066c7d4adb5ffcb02cfbcb55393d741c9cddeda2099d7d1d7505c1e683ba
              - name: kind
                value: task
              - name: arch
                value: amd64
            resolver: multi-arch-bundle
          when:
            - input: "true"
              operator: in
              values:
                - "false"
          workspaces:
            - name: source
              workspace: workspace
        - name: label-check
          runAfter:
            - inspect-image
          taskRef:
            kind: Task
            params:
              - name: name
                value: label-check
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-label-check:0.1@sha256:0c0739fdda24cd1e3587bbab9b07d4493efc21884baac7723f4b446e95bf1fd3
              - name: kind
                value: task
            resolver: bundles
          when:
            - input: "true"
              operator: in
              values:
                - "false"
          workspaces:
            - name: workspace
              workspace: workspace
        - name: optional-label-check
          params:
            - name: POLICY_NAMESPACE
              value: optional_checks
          runAfter:
            - inspect-image
          taskRef:
            kind: Task
            params:
              - name: name
                value: label-check
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-label-check:0.1@sha256:0c0739fdda24cd1e3587bbab9b07d4493efc21884baac7723f4b446e95bf1fd3
              - name: kind
                value: task
            resolver: bundles
          when:
            - input: "true"
              operator: in
              values:
                - "false"
          workspaces:
            - name: workspace
              workspace: workspace
        - name: deprecated-base-image-check
          params:
            - name: BASE_IMAGES_DIGESTS
              value: $(tasks.build-container.results.BASE_IMAGES_DIGESTS)
          taskRef:
            kind: Task
            params:
              - name: name
                value: deprecated-image-check
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-deprecated-image-check:0.2@sha256:40856a6c6b4452361a2cdb17b927a35fd03edc3eec2e5bf94f96d211cc1d1d52
              - name: kind
                value: task
            resolver: bundles
          when:
            - input: "true"
              operator: in
              values:
                - "false"
          workspaces:
            - name: test-ws
              workspace: workspace
        - name: clair-scan
          params:
            - name: image-digest
              value: $(tasks.build-container.results.IMAGE_DIGEST)
            - name: image-url
              value: $(tasks.build-container.results.IMAGE_URL)
          runAfter:
            - build-container
          taskRef:
            kind: Task
            params:
              - name: name
                value: clair-scan
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-clair-scan:0.1@sha256:2016d1d4a1fc02ed353d7aede4bc5f81c5a335f6bcf4a9a2c97d33364afc3210
              - name: kind
                value: task
            resolver: bundles
          when:
            - input: "true"
              operator: in
              values:
                - "false"
        - name: sast-snyk-check
          runAfter:
            - clone-repository
          taskRef:
            kind: Task
            params:
              - name: name
                value: sast-snyk-check
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-sast-snyk-check:0.1@sha256:6e07c36a0792d6abdc0b59a6d8f8dc99c07b3810a8495f1903a32d8abb0fa004
              - name: kind
                value: task
            resolver: bundles
          when:
            - input: "true"
              operator: in
              values:
                - "false"
          workspaces:
            - name: workspace
              workspace: workspace
        - name: clamav-scan
          params:
            - name: image-digest
              value: $(tasks.build-container.results.IMAGE_DIGEST)
            - name: image-url
              value: $(tasks.build-container.results.IMAGE_URL)
          runAfter:
            - build-container
          taskRef:
            kind: Task
            params:
              - name: name
                value: clamav-scan
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-clamav-scan:0.1@sha256:a666a7dd4fd633d268d1ba26eaaa5ca2dd848c76b7fb2f04b8b37b7ce1c65f9a
              - name: kind
                value: task
            resolver: bundles
          when:
            - input: "true"
              operator: in
              values:
                - "false"
        - name: sbom-json-check
          params:
            - name: IMAGE_URL
              value: $(tasks.build-container.results.IMAGE_URL)
            - name: IMAGE_DIGEST
              value: $(tasks.build-container.results.IMAGE_DIGEST)
          runAfter:
            - build-container
          taskRef:
            kind: Task
            params:
              - name: name
                value: sbom-json-check
              - name: bundle
                value: quay.io/redhat-appstudio-tekton-catalog/task-sbom-json-check:0.1@sha256:30829c02906bfb5761a2c3509ec00fa7b41a97ae1c931cdedcd007664fdbc292
              - name: kind
                value: task
            resolver: bundles
          when:
            - input: "true"
              operator: in
              values:
                - "false"
      workspaces:
        - name: workspace
        - name: git-auth
          optional: true
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
