apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: sample-provision-
  namespace: multi-platform-controller
spec:
  taskRef:
    name: provision-shared-host
  params:
    - name: SECRET_NAME
      value: foo
    - name: TASKRUN_NAME
      value: user1
    - name: NAMESPACE
      value: test-jvm-namespace
    - name: HOST
      value: 	150.240.147.198
    - name: USER
      value: root
  workspaces:
    - name: ssh
      secret:
        secretName: awskeys
  serviceAccountName: multi-platform-controller
