name: Lint renovate
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/renovate.json

jobs:
  lint-renovate:
    name: Verify renovate manifests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Install check-jsonschema
        run: pipx install check-jsonschema==0.37.4

      - name: Lint manifests
        run: |
          check-jsonschema --builtin-schema vendor.renovate .github/renovate.json
