name: Validate PR - Testing Phase With SeaLights Monitoring - golang CI

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

  repository_dispatch:
    types: [trigger-mpc-test-with-sealights-ci]

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checkout_and_test:
    name: Golang Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Handle invalid context
        if: ${{ !github.event.pull_request.head.sha || !github.event.pull_request.number }}
        run: |
          echo "Invalid context for this workflow run. Exiting."
          exit 1
      - name: Check out code of the forked repository's head branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}  
          ref: ${{ github.event.pull_request.head.ref }}  
      - name: Install Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version-file: "./go.mod"
      - name: Write SeaLights token into file
        run: echo "${SEALIGHTS_AGENT_TOKEN}" > sltoken.txt
        env:
          SEALIGHTS_AGENT_TOKEN: '${{secrets.SEALIGHTS_AGENT_TOKEN}}'
      - name: Initiating and configuring SeaLights
        if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha && github.event.pull_request.number }}
        run: ./mpc_testing_with_sealights.sh --mode pull_request --pr-number ${PULL_REQUEST_NUMBER} --commit-sha ${LATEST_COMMIT_SHA}
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
          LATEST_COMMIT_SHA: ${{github.event.pull_request.head.sha}}
      - name: Codecov
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4
